
HuesInfo = {}

HuesInfo.Data = {
-- SPECIAL
[0] = 		L"Plain Default Color",
[1] = 		L"Jet Black (Black Dye Tub)",
[11] = 		L"Sigil Purple (Faction Sigil Bug)",
[1153] = 	L"Pure White (AOS Cloth)",
[232] = 	L"Crimson Red (Crimson Cincture)",
[1278] = 	L"Gauntlet Purple (Gauntlets of Nobility)",
[1270] = 	L"Ornate Green (Ornate Crown of the Harrower)",
[1152] = 	L"Glacial Blue (Glacial Staff)",
[250] = 	L"Museum Chaos Shield Gold",
[1177] = 	L"Europa Gold (Soles of Providence)",
[1194] = 	L"Conjurer Red (Conjurer's Garb)",
[2075] = 	L"Chaos Red (Sign of Chaos)",
[2075] = 	L"Abyssal Shadow (Abyssal Cloth)",
[1174] = 	L"Amber (Burning Amber)",
[1426] = 	L"Ranger Green (Ranger Armor)",

-- REWARD CLOTH
[1161] = 	L"Blaze (Reward Cloth lvl 5)",
[1154] = 	L"Ice Blue (Reward Cloth lvl 5, Plant Pigment)",
[1175] = 	L"Characoal (Reward Cloth lvl 4 or Plant Pigment)",
[1172] = 	L"Blood Red (Reward Cloth lvl 4)",
[1165] = 	L"Light blue (Reward Cloth lvl 3)",
[1166] = 	L"Neon Pink (Reward Cloth lvl 3)",
[1163] = 	L"Rare Magenta (Reward Cloth lvl 2 or Plant Pigment)",
[1157] = 	L"Maroon (Reward Cloth lvl 2)",
[1164] = 	L"Navy Green (Reward Cloth lvl 1)",
[1162] = 	L"Dark Teal (Reward Cloth lvl 1)",
[1160] = 	L"Serpent Green (Reward Cloth lvl 1)",
[1155] = 	L"Green (Reward Cloth lvl 1)",

-- NEON PIGMENTS
[1150] = 	L"Luna White (Neon Pigment, Reward Cloth lvl 5, Plant Pigment)",
[1167] = 	L"Dryad Green (Neon Pigment or Reward Cloth lvl 4)",
[33] = 		L"Berserker Red (Neon Pigment)",
[1281] = 	L"Paragon Gold (Neon Pigment)",
[1420] = 	L"Nox Green (Neon Pigment)",
[1359] = 	L"Fire Orange (Neon Pigment)",
[1644] = 	L"Rum Red (Neon Pigment)",
[1266] = 	L"Invulnerability Blue (Neon Pigment)",
[1158] = 	L"Violet Courage Purple (Neon Pigment or Reward Cloth lvl 2)",
[1109] = 	L"Shadow Dancer Black (Neon Pigment)",

-- METAL PIGMENTS
[2401] = 	L"Faded Coal (Metal Pigment)",
[2410] = 	L"Coal (Metal Pigment)",
[2415] = 	L"Faded Gold (Metal Pigment)",
[2421] = 	L"Storm Bronze (Metal Pigment)",
[2426] = 	L"Rose (Metal Pigment)",
[2411] = 	L"Midnight Coal (Metal Pigment)",
[2420] = 	L"Faded Bronze (Metal Pigment)",
[2425] = 	L"Faded Rose (Metal Pigment)",
[2430] = 	L"Deep Rose (Metal Pigment)",

-- LESSER NEON PIGMENTS
[325] = 	L"Fresh Plum (Lesser Neon Pigment)",
[1001] = 	L"Silver (Lesser Neon Pigment)",
[1008] = 	L"Deep Brown (Lesser Neon Pigment)",
[1050] = 	L"Burnt Brown (Lesser Neon Pigment)",
[456] = 	L"Light Green (Lesser Neon Pigment)",
[1209] = 	L"Fresh Rose (Lesser Neon Pigment)",
[591] = 	L"Pale Blue (Lesser Neon Pigment)",
[551] = 	L"Noble Gold (Lesser Neon Pigment)",
[46] = 		L"Pale Orange (Lesser Neon Pigment)",
[5] = 		L"Chaos Blue (Lesser Neon Pigment)",

-- HAOCHI PIGMENTS
[1108] = 	L"Ninja Black (Haochi Pigment)",
[1156] = 	L"Midnight Blue (Haochi Pigment or Reward Cloth lvl 4)",
[1148] = 	L"Dark Reddis-Brown (Haochi Pigment)",
[1801] = 	L"Smoky Gold (Haochi Pigment)",
[1000] = 	L"Ghost's Gray (Haochi Pigment)",
[1196] = 	L"Olive (Haochi Pigment)",
[1173] = 	L"Emerald (Haochi Pigment or Reward Cloth lvl 2)",
[1195] = 	L"Ocean Blue (Haochi Pigment)",
[1168] = 	L"Pretty Pink (Haochi Pigment or Reward Cloth lvl 3)",
[1169] = 	L"Yellow (Haochi Pigment or Reward Cloth lvl 3)",

-- PLANT PIGMENTS
[2217] = 	L"Dark Yellow (Plant Pigment)",
[56] = 		L"Ice Yellow (Plant Pigment)",
[261] = 	L"Ice Green (Plant Pigment)",
[1425] = 	L"Dark Green (Plant Pigment)",
[1317] = 	L"Dark Blue (Plant Pigment)",
[1509] = 	L"Dark Orange (Plant Pigment)",
[346] = 	L"Ice Orange (Plant Pigment)",
[1254] = 	L"Dark Purple (Plant Pigment)",
[511] = 	L"Ice Purple (Plant Pigment)",
[1141] = 	L"Dark Red (Plant Pigment)",
[335] = 	L"Ice Red (Plant Pigment)",
[746] = 	L"Off White (Plant Pigment)",
[1105] = 	L"Ice Black (Plant Pigment)",
[2422] = 	L"Metal (Plant Pigment)",
[2101] = 	L"Plain (Plant Pigment)",
[2125] = 	L"Yellow (Plant Pigment)",
[2128] = 	L"Green (Plant Pigment)",
[2122] = 	L"Blue (Plant Pigment)",
[1128] = 	L"Orange (Plant Pigment)",
[15] = 		L"Purple (Plant Pigment)",
[1652] = 	L"Red (Plant Pigment)",
[341] = 	L"Rare Pink (Plant Pigment)",
[391] = 	L"Rare Aqua (Plant Pigment)",
[1358] = 	L"Rare Fire Red (Plant Pigment)",
[253] = 	L"Bright Yellow (Plant Pigment)",
[671] = 	L"Bright Green (Plant Pigment)",
[1310] = 	L"Bright Blue (Plant Pigment)",
[1501] = 	L"Bright Orange (Plant Pigment)",
[316] = 	L"Bright Purple (Plant Pigment)",
[1646] = 	L"Bright Red (Plant Pigment)",

-- METALS/LEATHER/WOOD
[2425] = 	L"Agapite (Metal)",
[2413] = 	L"Copper (Metal)",
[2213] = 	L"Gold (Metal)",
[2418] = 	L"Bronze (Metal)",
[2419] = 	L"Dull Copper (Metal)",
[2406] = 	L"Shadow (Metal)",
[2207] = 	L"Verite (Metal)",
[2219] = 	L"Valorite (Metal)",
[2117] = 	L"Horned (Leather)",
[2129] = 	L"Barbed (Leather)",
[2220] = 	L"Spined (Leather)",
[2010] = 	L"Oak (Wood)",
[1191] = 	L"Ash (Wood)",
[1192] = 	L"Yew (Wood)",
[1193] = 	L"Heartwood (Wood)",
[1194] = 	L"Bloodwood (Wood)",
[1151] = 	L"Frostwood (Reward Cloth lvl 5 or Wood)",
[1936] = 	L"Hunter Green",
[1951] = 	L"Lavender",
[1964] = 	L"Phoenix Red/Vibrant Crimson",
[1983] = 	L"Slate Blue",
[1944] = 	L"Polished Bronze",
[1929] = 	L"Deep Violet",
[1979] = 	L"Black and Green",
[1916] = 	L"Glossy Blue",
[1960] = 	L"Shadowy Blue",
[1930] = 	L"Gleaming Fuschia",
[1967] = 	L"Aura of Amber",
[1992] = 	L"Murky Seagreen",
[1919] = 	L"Glossy Fuchsia",
[1939] = 	L"Deep Blue",
[1970] = 	L"Vibrant Seagreen",
[1989] = 	L"Murky Amber",
[1910] = 	L"Reflective Shadow",
[2720] = 	L"Mother of Pearl",
[2723] = 	L"Star Blue",
[1923] = 	L"Liquid Sunshine",
[2068] = 	L"Dark Void",
}